config/routes.rb
Rails.application.routes.draw do

	root 'welcome#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get 'welcome_controller/updateSocial', :controller => :welcome, :action => :updateSocial
  post 'welcome_controller/sendVals', :controller => :welcome, :action => :sendVals

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,# :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        #user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linked_in].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  require 'twitter'

  @twitter_factor = 0
  MAX_TWEETS = 25

  $first = ""
  $second = ""
  $third = ""

  def makeClient
		client = Twitter::Streaming::Client.new do |config|
	    config.consumer_key       = 'QxcbFqox8Zc7ehMUbNFShHZzc'
	    config.consumer_secret    = 'dOgfPTDm1p8Gn3vKRWiGhjMhawlr9TNeZPpdqNIwx2kHEqoEYQ'
	    config.access_token        = '2362889286-Rse58rWvw75mbrb9otB92g2eV340TcuWXDHKPpJ'
	    config.access_token_secret  = 'A8WZ4M56VW1D9b58EgbduXm4QOU0FK7yLiOki3WX1xEza'
	    #config.auth_method        = :oauth
	  end  
	  return client
  end

  def sendVals
  	$first = params[:first]
  	$second = params[:second]
  	$third = params[:third]

  	updateSocial # run the first calc as soon as the 3 params are done
  end

  def updateSocial

  	@tweet_limit = MAX_TWEETS

  	  if (@twitter_factor)
		  client = makeClient

		  puts "attempting to log into twitter..."
		  
		  count = 0

		  indico_enabled = 0

		  if (indico_enabled)
		  	require 'indico'
		  	Indico.api_key = 'a20e64f1e4fd1dd002ec661f62caa444'
		   end

		  @statuses = []
		  @sentiments = []

		  topics = [$first, $second, $third]

		  puts "topics are: " + topics.join(",")

		  client.sample do |status| 
		 	#client.filter(track: topics.join(",")) do |status| 
		 		if status.is_a?(Twitter::Tweet) and count < @tweet_limit

		 			if status.text.to_s == ""
		 				continue
		 			end

		 			text = (status.text).to_s
		  			@statuses.push(text)

		  			if (indico_enabled)
		  				@sentiments.push(Indico.sentiment(text))
		  			else
		  				@sentiments.push(rand)
		  			end

		  			count += 1
		  			
		  			puts count
		  			puts status.text.to_s
		  		else
		  			break
		  		end
		  	end

		  	@tweet_limit = count
		 else


		 end

	  respond_to do |format|
	    format.js
	  end

  end

  def index

	  # count = 0

	  # require 'indico'
	  # Indico.api_key = 'a20e64f1e4fd1dd002ec661f62caa444'

	  # @statuses = []
	  # @sentiments = []

	 	# client.sample do |status| 
	 	# 	if status.is_a?(Twitter::Tweet) and count < @tweet_limit

	 	# 		if status.text.to_s == ""
	 	# 			continue
	 	# 		end

	 	# 		text = (status.text).to_s
	  # 			@statuses.push(text)
	  # 			@sentiments.push(Indico.sentiment(text))
	  # 			count += 1
	  # 			#puts count
	  # 			#puts status.text.to_s
	  # 		else
	  # 			break
	  # 		end
	  # 	end

	  # 	@tweet_limit = count

	  # 	#puts "loop finished"

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <!--<link rel="stylesheet" media="only screen and (max-width: 820px)" href="css/shrunk.css" />
    <link rel="stylesheet" media="only screen and (max-width: 520px)" href="css/mobile.css" />-->

  <title>YouCarryIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

        <header>
            <h2>You Carry It</h2>
            <nav>
              <% if current_user == nil or not user_signed_in? %>
              <%#= link_to "Sign in with Facebook", omniauth_authorize_path(User, :facebook) %>
              <% else %>
              Logged in as: <%= current_user.name %> [<%= link_to "Log out", destroy_user_session_path, :method => :delete  %>]
              <% end %>

              <div id="masthead">Made by <a href="http://jondtang.com">Jonathan Tang</a>, <a href="http://oliverbarnum.com">Oliver Barnum</a>, <a href="https://www.linkedin.com/pub/dan-shiferaw/9a/934/18b">Dan Shiferaw</a>, and <a href="https://github.com/foche">Tuan Anh Phan Le</a>.</div>

            </nav>
            
        </header>

            <div id="container">

<%= yield %>

    </div>

</body>
</html>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/welcome/_rails_data_partial.erb
<<<<<<< HEAD

<% for i in 0..(@tweet_limit-1) %>
<%= @sentiments[i].to_s.gsub('~', '') %>~
<%= @statuses[i].to_s.gsub('~', '') %>~
=======
<%#= render partial: 'posts/updateSocial', object: @user.posts.last, as: :post %>

<% for i in 0..(@tweet_limit-1) %>
<%= @sentiments[i].to_s %>, 
<%= @statuses[i].to_s %>, 
>>>>>>> origin/master
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<article>

<!-- <p><b>Twitter stream with Indico analysis (<%= @tweet_limit %> scraped)</b></p> -->


    <%= javascript_include_tag "bullet",     "data-turbolinks-track" => true %>
    <%= javascript_include_tag "enemy",      "data-turbolinks-track" => true %>
    <%= javascript_include_tag "cell",       "data-turbolinks-track" => true %>
    <%= javascript_include_tag "organelle",  "data-turbolinks-track" => true %>
    <%= javascript_include_tag "nutrients", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "canvasgame", "data-turbolinks-track" => true %>

<script>

    setInterval(function() {
    jQuery.ajax({
      url: "welcome_controller/updateSocial",
      type: "GET",
      dataType: "script"
    });

    }, 30000); // in milliseconds, focus on many tweets and few requests rather than vice versa

</script>

    <div id="threeOptions">

        <h2>What are your favorite things? </h2>

        <ul style="list-style-type: none;">
            <li>First:  <input id="first" type="text" name="first" value="Thomas Aquinas"></li>
            <li>Second: <input id="second" type="text" name="second" value="Dota 2"></li>
            <li>Third:  <input id="third" type="text" name="third" value="personal fitness"></li>
        </ul>
        <input type="button" value="Submit" id="button_1" onclick = "createGame();" >
    </div>

    <canvas id="canvasGame" width="800" height="600">></canvas>
    <p><b>Use the arrow keys to move!</b></p>

    
<div id = "rails-data"></div>

</article>

</html>

app/views/welcome/sendVals.js.erb
<%#= render partial: 'posts/updateSocial', object: @user.posts.last, as: :post %>

app/views/welcome/updateSocial.html.erb
<%#= render partial: 'posts/updateSocial', object: @user.posts.last, as: :post %>

<div id="rails-data">
 <%= render :partial => "rails_data_partial" %>
</div>

app/views/welcome/updateSocial.js.erb
<%#= render partial: 'posts/updateSocial', object: @user.posts.last, as: :post %>


$("#rails-data").html("<%= escape_javascript render :partial => "rails_data_partial" %>")